USE GameDB;

CREATE TABLE IF NOT EXISTS characters (
  char_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  account_id BIGINT UNSIGNED NOT NULL,
  name VARCHAR(32) NOT NULL,
  class_id INT NOT NULL,
  gender TINYINT NOT NULL,
  level INT NOT NULL DEFAULT 1,
  exp BIGINT NOT NULL DEFAULT 0,
  map_id INT NOT NULL DEFAULT 1,
  pos_x FLOAT NOT NULL DEFAULT 0,
  pos_y FLOAT NOT NULL DEFAULT 0,
  pos_z FLOAT NOT NULL DEFAULT 0,
  hp INT NOT NULL DEFAULT 100,
  mp INT NOT NULL DEFAULT 100,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (char_id),
  UNIQUE KEY uq_characters_name (name),
  KEY idx_characters_account_id (account_id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS character_stats (
  char_id BIGINT UNSIGNED NOT NULL,
  str_stat INT NOT NULL DEFAULT 5,
  agi_stat INT NOT NULL DEFAULT 5,
  vit_stat INT NOT NULL DEFAULT 5,
  int_stat INT NOT NULL DEFAULT 5,
  free_points INT NOT NULL DEFAULT 0,
  PRIMARY KEY (char_id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS inventory_items (
  item_uid BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  char_id BIGINT UNSIGNED NOT NULL,
  item_id INT NOT NULL,
  slot INT NULL,
  count INT NOT NULL DEFAULT 1,
  bind_state TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (item_uid),
  KEY idx_inventory_char_id (char_id),
  KEY idx_inventory_item_id (item_id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS quests_state (
  char_id BIGINT UNSIGNED NOT NULL,
  quest_id INT NOT NULL,
  state TINYINT NOT NULL DEFAULT 0,
  progress INT NOT NULL DEFAULT 0,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (char_id, quest_id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS world_runtime_flags (
  flag_key VARCHAR(64) NOT NULL,
  flag_value VARCHAR(255) NOT NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (flag_key)
) ENGINE=InnoDB;
